# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "example-streamer-uses"
rust-version.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true

[[bin]]
name = "someip_client"
required-features = ["vsomeip-transport"]

[[bin]]
name = "someip_publisher"
required-features = ["vsomeip-transport"]

[[bin]]
name = "someip_notifier"
required-features = ["vsomeip-transport"]

[[bin]]
name = "someip_notifyee"
required-features = ["vsomeip-transport"]

[[bin]]
name = "someip_server"
required-features = ["vsomeip-transport"]

[[bin]]
name = "someip_subscriber"
required-features = ["vsomeip-transport"]

[[bin]]
name = "zenoh_client"
required-features = ["zenoh-transport"]

[[bin]]
name = "zenoh_publisher"
required-features = ["zenoh-transport"]

[[bin]]
name = "zenoh_server"
required-features = ["zenoh-transport"]

[[bin]]
name = "zenoh_notifier"
required-features = ["zenoh-transport"]

[[bin]]
name = "zenoh_notifyee"
required-features = ["zenoh-transport"]

[[bin]]
name = "iceoryx2_publisher"
required-features = ["iceoryx2-selected-wire"]

[[bin]]
name = "iceoryx2_subscriber"
required-features = ["iceoryx2-selected-wire"]

[[bin]]
name = "iceoryx2_notifier"
required-features = ["iceoryx2-selected-wire"]

[[bin]]
name = "iceoryx2_notifyee"
required-features = ["iceoryx2-selected-wire"]

[[bin]]
name = "iceoryx2_client"
required-features = ["iceoryx2-selected-wire"]

[[bin]]
name = "iceoryx2_server"
required-features = ["iceoryx2-selected-wire"]

[[bin]]
name = "lola_publisher"
required-features = ["lola-selected-wire"]

[[bin]]
name = "lola_subscriber"
required-features = ["lola-selected-wire"]

[[bin]]
name = "lola_notifier"
required-features = ["lola-selected-wire"]

[[bin]]
name = "lola_notifyee"
required-features = ["lola-selected-wire"]

[[bin]]
name = "lola_client"
required-features = ["lola-selected-wire"]

[[bin]]
name = "lola_server"
required-features = ["lola-selected-wire"]

[[bin]]
name = "zenoh_subscriber"
required-features = ["zenoh-transport"]

[[bin]]
name = "mqtt_client"
required-features = ["mqtt-transport"]

[[bin]]
name = "mqtt_publisher"
required-features = ["mqtt-transport"]

[[bin]]
name = "mqtt_notifier"
required-features = ["mqtt-transport"]

[[bin]]
name = "mqtt_notifyee"
required-features = ["mqtt-transport"]

[[bin]]
name = "mqtt_server"
required-features = ["mqtt-transport"]

[[bin]]
name = "mqtt_subscriber"
required-features = ["mqtt-transport"]

[features]
selected-wire-common = ["up-rust/owned-frame-transport", "up-rust/selected-wire-user-api"]
zenoh-transport = ["selected-wire-common", "up-transport-zenoh", "up-transport-zenoh/benchmark-owned", "up-transport-zenoh/zero-copy", "up-wire-xcdrv2", "zenoh"]
zenoh-owned-frame = ["selected-wire-common", "zenoh-transport", "up-transport-zenoh/benchmark-owned", "up-wire-xcdrv2"]
zenoh-zero-copy = ["selected-wire-common", "zenoh-transport", "up-transport-zenoh/zero-copy", "up-wire-xcdrv2"]
zenoh-selected-wire = ["zenoh-owned-frame", "zenoh-zero-copy"]
iceoryx2-owned-frame = ["selected-wire-common", "up-transport-iceoryx2-rust", "up-transport-iceoryx2-rust/benchmark-owned", "up-wire-xcdrv2"]
iceoryx2-zero-copy = ["selected-wire-common", "up-transport-iceoryx2-rust", "up-wire-xcdrv2"]
iceoryx2-selected-wire = ["iceoryx2-owned-frame", "iceoryx2-zero-copy"]
lola-transport = ["selected-wire-common", "up-transport-lola-rust", "up-transport-lola-rust/zero-copy", "up-wire-xcdrv2"]
lola-owned-frame = ["lola-transport", "up-transport-lola-rust/benchmark-owned"]
lola-zero-copy = ["lola-transport"]
lola-selected-wire = ["lola-owned-frame", "lola-zero-copy"]
vsomeip-transport = ["up-transport-vsomeip"]
bundled-vsomeip = ["up-transport-vsomeip/bundled"]
mqtt-transport = ["up-transport-mqtt5"]

[dependencies]
async-trait = { workspace = true }
chrono = { version = "0.4" }
clap = { version = "4.5.9", features = ["derive"] }
hello-world-protos = { path = "../utils/hello-world-protos" }
json5 = { workspace = true }
protobuf = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
up-rust = { workspace = true }
up-transport-iceoryx2-rust = { workspace = true, optional = true }
up-transport-lola-rust = { git = "https://github.com/PLeVasseur/up-transport-lola-rust.git", rev = "e12afc768756ec8f86ed681e9437fd18ae9a6613", optional = true }
up-transport-zenoh = { workspace = true, optional = true }
up-transport-vsomeip = { workspace = true, optional = true }
up-transport-mqtt5 = { workspace = true, optional = true }
up-wire-xcdrv2 = { git = "ssh://git@github.com/PLeVasseur/up-wire-xcdrv2-rust.git", rev = "94bf9cf09731f0bc22ced6858ca257c8423b40f8", optional = true }
zenoh = { workspace = true, optional = true }
