# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "2"
members = [
    "example-streamer-uses",
    "utils/hello-world-protos",
    "utils/integration-test-utils",
    "example-streamer-implementations",
    "utils/criterion-guardrail",
    "utils/configurable-streamer-wire-support",
    "utils/streamer-transport-test-orchestrator",
    "utils/transport-smoke-suite",
    "configurable-streamer",
    "up-linux-streamer-plugin",
    "up-streamer",
    "utils/usubscription-static-file",
]

[workspace.package]
rust-version = "1.88"
version = "0.1.0"
repository = "https://github.com/eclipse-uprotocol/up-streamer-rust"
homepage = "https://github.com/eclipse-uprotocol"
edition = "2021"
keywords = ["uProtocol", "SDV", "routing", "streamer"]
license = "Apache-2.0"

[workspace.dependencies]
async-trait = { version = "0.1" }
bytes = { version = "1.11" }
clap = { version = "4.5" }
futures = { version = "0.3.30" }
lazy_static = { version = "1.5.0" }
json5 = { version = "0.4.1" }
serde = { version = "1.0.154", features = ["derive"] }
serde_json = { version = "1.0.94" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1.7.0" }
tokio = { version = "1.44", default-features = false, features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
    "macros",
] }
protobuf = { version = "3.7.2", features = ["with-bytes"] }
up-rust = { git = "https://github.com/PLeVasseur/up-rust.git", rev = "14331c5efc704487a6e1abb20cb8c129207885da", default-features = false }
up-transport-zenoh = { git = "https://github.com/PLeVasseur/up-client-zenoh-rust.git", rev = "33cc4238e1aed2b1d64672412f2595966cba3901" }
up-transport-iceoryx2-rust = { git = "https://github.com/PLeVasseur/up-transport-iceoryx2-rust.git", rev = "0bda7361659aa6515e523b8f1f496a539f215877" }
up-transport-vsomeip = { git = "https://github.com/PLeVasseur/up-client-vsomeip-rust.git", rev = "146f9701fbcb0244a20e8810f8ba59eb7910b2de", default-features = false }
up-transport-mqtt5 = { git = "https://github.com/PLeVasseur/up-client-mqtt5-rust.git", rev = "55b5b76bc3009b273de9807d05e76852d8ecfad4" }
up-transport-dds = { git = "https://github.com/PLeVasseur/up-transport-dds-rust.git", rev = "fdcd6786373c38bfa4930fc86ca2f82c90f0297f" }
up-wire-xcdrv2 = { git = "https://github.com/PLeVasseur/up-wire-xcdrv2-rust.git", rev = "27942d8e9f3a119ab6f51aa1ee01c7872f841dd7" }
up-wire-arrow = { git = "https://github.com/PLeVasseur/up-wire-arrow-rust.git", rev = "0941f2411950c0aab48d906693e857ac2c0edb46" }
up-wire-omgidl = { git = "https://github.com/PLeVasseur/up-wire-omgidl-rust.git", rev = "c5b944beba7996ee5ad0830a5db18bf7b066e5d4" }
zenoh = { version = "1.2.1", features = [
    "default",
    "plugins",
    "unstable",
    "internal",
] }
zenoh-core = { version = "1.2.1" }
zenoh-plugin-trait = { version = "1.2.1" }
zenoh-result = { version = "1.2.1" }
zenoh-util = { version = "1.2.1" }

[patch."ssh://git@github.com/PLeVasseur/up-rust.git"]
up-rust = { git = "https://github.com/PLeVasseur/up-rust.git", rev = "14331c5efc704487a6e1abb20cb8c129207885da" }

[profile.dev]
debug = true
opt-level = 0

[profile.matrix]
inherits = "dev"
debug = 0
strip = "debuginfo"
incremental = false

[profile.fast]
inherits = "release"
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false

[profile.release]
debug = false     # If you want debug symbol in release mode, set the env variable: RUSTFLAGS=-g
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
