# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "2"
members = [
    "example-streamer-uses",
    "utils/hello-world-protos",
    "utils/integration-test-utils",
    "example-streamer-implementations",
    "utils/criterion-guardrail",
    "utils/configurable-streamer-wire-support",
    "utils/streamer-transport-test-orchestrator",
    "utils/transport-smoke-suite",
    "configurable-streamer",
    "up-linux-streamer-plugin",
    "up-streamer",
    "utils/usubscription-static-file",
]

[workspace.package]
rust-version = "1.88"
version = "0.1.0"
repository = "https://github.com/eclipse-uprotocol/up-streamer-rust"
homepage = "https://github.com/eclipse-uprotocol"
edition = "2021"
keywords = ["uProtocol", "SDV", "routing", "streamer"]
license = "Apache-2.0"

[workspace.dependencies]
async-trait = { version = "0.1" }
bytes = { version = "1.11" }
clap = { version = "4.5" }
futures = { version = "0.3.30" }
lazy_static = { version = "1.5.0" }
json5 = { version = "0.4.1" }
serde = { version = "1.0.154", features = ["derive"] }
serde_json = { version = "1.0.94" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1.7.0" }
tokio = { version = "1.44", default-features = false, features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
    "macros",
] }
protobuf = { version = "3.7.2", features = ["with-bytes"] }
up-rust = { git = "https://github.com/PLeVasseur/up-rust.git", rev = "9e423a569eb9eb9c01a1585c74ac01a574ae6b8b", default-features = false }
up-transport-zenoh = { git = "https://github.com/PLeVasseur/up-client-zenoh-rust.git", rev = "c55652be534e15643a5ce3f6077c22a169be470a" }
up-transport-iceoryx2-rust = { git = "https://github.com/PLeVasseur/up-transport-iceoryx2-rust.git", rev = "4a0e32f2d398b745923c9edfd1b94a850ce6627a" }
up-transport-vsomeip = { git = "https://github.com/PLeVasseur/up-client-vsomeip-rust.git", rev = "638ee69c24dacc57e0bd8c289cc4f0afc0ad8662", default-features = false }
up-transport-mqtt5 = { git = "https://github.com/PLeVasseur/up-client-mqtt5-rust.git", rev = "23c2ec0e9633e86c9e174a712dba74fd6206da49" }
up-transport-dds = { git = "https://github.com/PLeVasseur/up-transport-dds-rust.git", rev = "126a5488e75b1aa3b112e5bb7ce2c09e8ae52d68" }
up-wire-xcdrv2 = { git = "https://github.com/PLeVasseur/up-wire-xcdrv2-rust.git", rev = "eaf4887f80ec29489adfac2d9b00cdd21ec2b229" }
up-wire-arrow = { git = "https://github.com/PLeVasseur/up-wire-arrow-rust.git", rev = "b656e69185180a89ac5ecea750e8e956a8fadb6e" }
up-wire-omgidl = { git = "https://github.com/PLeVasseur/up-wire-omgidl-rust.git", rev = "9ebab5ce8cee9a93eb20211cde5713c9e1dcb173" }
zenoh = { version = "1.2.1", features = [
    "default",
    "plugins",
    "unstable",
    "internal",
] }
zenoh-core = { version = "1.2.1" }
zenoh-plugin-trait = { version = "1.2.1" }
zenoh-result = { version = "1.2.1" }
zenoh-util = { version = "1.2.1" }

[patch."ssh://git@github.com/PLeVasseur/up-rust.git"]
up-rust = { git = "https://github.com/PLeVasseur/up-rust.git", rev = "9e423a569eb9eb9c01a1585c74ac01a574ae6b8b" }

[profile.dev]
debug = true
opt-level = 0

[profile.matrix]
inherits = "dev"
debug = 0
strip = "debuginfo"
incremental = false

[profile.fast]
inherits = "release"
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false

[profile.release]
debug = false     # If you want debug symbol in release mode, set the env variable: RUSTFLAGS=-g
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
