# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "configurable-streamer"
rust-version.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true

[features]
default = []
experimental-copy-minimized-routing = ["up-streamer/experimental-copy-minimized-routing"]
zenoh-zero-copy = ["dep:up-wire-xcdrv2", "up-transport-zenoh/zero-copy", "configurable-streamer-wire-support/zenoh-zero-copy"]
iceoryx2-zero-copy = [
    "configurable-streamer-wire-support/iceoryx2-zero-copy",
    "dep:up-transport-iceoryx2-rust",
    "dep:up-wire-xcdrv2",
]
lola-transport = [
    "configurable-streamer-wire-support/lola-transport",
    "dep:up-transport-lola-rust",
    "dep:up-wire-xcdrv2",
    "up-transport-lola-rust/zero-copy",
]
owned-frame-transport = [
    "configurable-streamer-wire-support/owned-frame-transport",
    "up-streamer/owned-frame-transport",
]
zenoh-owned-frame = [
    "owned-frame-transport",
    "configurable-streamer-wire-support/zenoh-owned-frame",
    "dep:up-wire-xcdrv2",
    "up-transport-zenoh/benchmark-owned",
]
iceoryx2-owned-frame = [
    "owned-frame-transport",
    "configurable-streamer-wire-support/iceoryx2-owned-frame",
    "dep:up-transport-iceoryx2-rust",
    "dep:up-wire-xcdrv2",
    "up-transport-iceoryx2-rust/benchmark-owned",
]
lola-owned-frame = [
    "owned-frame-transport",
    "configurable-streamer-wire-support/lola-owned-frame",
    "dep:up-transport-lola-rust",
    "dep:up-wire-xcdrv2",
    "up-transport-lola-rust/benchmark-owned",
    "up-transport-lola-rust/zero-copy",
]

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
json5 = { workspace = true }
protobuf = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
up-rust = { workspace = true }
up-streamer = { path = "../up-streamer" }
configurable-streamer-wire-support = { path = "../utils/configurable-streamer-wire-support" }
up-transport-iceoryx2-rust = { workspace = true, optional = true }
up-transport-lola-rust = { git = "https://github.com/PLeVasseur/up-transport-lola-rust.git", rev = "ee21e6e6e14a43d22368d43a8ccdf8d9d64f26b8", optional = true }
up-transport-zenoh = { workspace = true }
up-wire-xcdrv2 = { git = "ssh://git@github.com/PLeVasseur/up-wire-xcdrv2-rust.git", rev = "3a89a4699486d0bf37447a5c2d03ce4261b0dcfa", optional = true }
up-transport-mqtt5 = { workspace = true }
zenoh = { workspace = true }
usubscription-static-file = { path = "../utils/usubscription-static-file" }

[dev-dependencies]
hello-world-protos = { path = "../utils/hello-world-protos" }
