# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "configurable-streamer-wire-support"
rust-version.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true

[features]
default = []
zenoh-zero-copy = ["dep:up-transport-zenoh", "dep:up-wire-xcdrv2", "up-transport-zenoh/zero-copy"]
iceoryx2-zero-copy = ["dep:up-transport-iceoryx2-rust", "dep:up-wire-xcdrv2"]
lola-transport = ["dep:up-transport-lola-rust", "dep:up-wire-xcdrv2", "up-transport-lola-rust/zero-copy"]
owned-frame-transport = ["dep:up-wire-xcdrv2", "up-streamer/owned-frame-transport"]
zenoh-owned-frame = ["owned-frame-transport", "dep:up-transport-zenoh", "up-transport-zenoh/benchmark-owned"]
iceoryx2-owned-frame = ["owned-frame-transport", "dep:up-transport-iceoryx2-rust", "up-transport-iceoryx2-rust/benchmark-owned"]
lola-owned-frame = ["owned-frame-transport", "dep:up-transport-lola-rust", "up-transport-lola-rust/benchmark-owned", "up-transport-lola-rust/zero-copy"]

[dependencies]
up-rust = { workspace = true }
up-streamer = { path = "../../up-streamer", features = ["experimental-copy-minimized-routing"] }
up-transport-zenoh = { workspace = true, optional = true }
up-transport-iceoryx2-rust = { workspace = true, optional = true }
up-transport-lola-rust = { git = "https://github.com/PLeVasseur/up-transport-lola-rust.git", rev = "fbe47df294a962cee880567f240003beeeb72eb8", optional = true }
up-wire-xcdrv2 = { git = "ssh://git@github.com/PLeVasseur/up-wire-xcdrv2-rust.git", rev = "cd89d2494a089163d1c6a7473fd9ae50ebd6897f", optional = true }
